/*
 * simplewebfactory.cpp
 *
 *  Created on: Jul 20, 2018
 *      Author: hhdang
 */

#include <iostream>
#include <vector>
#include <algorithm>
#include <fstream>
#include <sstream>

#include "simplewebfactory.h"

bool simpleWebFactory::file_to_string(std::string filename, std::string &output)
{
    std::string line;
    std::ifstream file(filename);
    std::ostringstream ss;

    output.clear();

    if (file.is_open()) {
        while (getline(file, line)) {
            ss << line;
            ss << std::endl;
        }
        file.close();
        output = ss.str();
    } else {
        return false;
    }

    return true;
}

simpleWebFactory::simpleWebFactory()
{
    std::string html_file;

    html_file = INTERNAL_RESOURCE"/header.html";
    simpleWebFactory::file_to_string(html_file, this->html_header_str);

    html_file = INTERNAL_RESOURCE"/footer.html";
    simpleWebFactory::file_to_string(html_file, this->html_footer_str);

    html_file = INTERNAL_RESOURCE"/navbar.html";
    simpleWebFactory::file_to_string(html_file, this->html_navbar_str);

    this->init_url_html_map();
}

simpleWebFactory::~simpleWebFactory()
{

}

simpleWebFactory *simpleWebFactory::s_instance = 0;

simpleWebFactory* simpleWebFactory::getInstance()
{
    if (s_instance == 0) {
        s_instance = new simpleWebFactory();
    }

    return s_instance;
}

const char* simpleWebFactory::get_html_header_str()
{
    return this->html_header_str.c_str();
}

const char* simpleWebFactory::get_html_footer_str()
{
    return this->html_footer_str.c_str();
}

const char* simpleWebFactory::get_html_navbar_str()
{
    return this->html_navbar_str.c_str();
}

const char* simpleWebFactory::get_html_str(const char * url)
{
    const char* main_content = NULL;
    std::map<std::string, std::string>::iterator it;

    it = this->url_html_map.find(url);
    if (it == this->url_html_map.end()) {
        return NULL;
    }

    main_content = it->second.c_str();

    static std::string html_str;

    html_str = "<!doctype html>"
            "<html lang=\"en\">";
    html_str += this->get_html_header_str();

    html_str += "<body>";
    html_str += this->get_html_navbar_str();

    html_str += "<div class=\"container-fluid\"><div class=\"row\">";

    // need to be generated by code
    html_str += "   <nav class=\"col-md-2 d-none d-md-block bg-light sidebar\">"
            "   <div class=\"sidebar-sticky\">"
            "      <ul class=\"nav flex-column\">"
            "          <li class=\"nav-item\">"
            "              <a class=\"nav-link active\" href=\"#\">"
            "                  <span data-feather=\"home\"></span>Dashboard <span class=\"sr-only\">(current)</span>"
            "              </a>"
            "          </li>"
            "      </ul>"
            "   </div>"
            "   </nav>"
            "   "
            "   <main role=\"main\" class=\"col-md-9 ml-sm-auto col-lg-10 pt-3 px-4\">";
    // "      <div class=\"d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom\">"
    // "          <h1 class=\"h2\">Dashboard</h1>"
    // "      </div>"
    html_str += main_content;
    html_str += "   </main>";

    html_str += "</div";

    html_str += this->get_html_footer_str();

    html_str += "</body>";
    html_str += "</html>";

    return html_str.c_str();
}
